import './globals.css';
import { Montserrat } from 'next/font/google';

const mont = Montserrat({
    subsets: ['latin'],
    variable: "--font-mont",
})

export const metadata = {
    title: "Kaye's Portfolio",
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
