import './globals.css';
import { Montserrat } from 'next/font/google';
import Head from "next/head";
import NavBar from "@/app/components/NavBar";

const mont = Montserrat({
    subsets: ['latin'],
    variable: "--font-mont",
})

export const metadata = {
    title: "Kaye's Portfolio",
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang={"en"}>
          <Head>
              <meta name={"viewport"} content={"width=device-width, initial-scale=1"} />
              <link rel={"icon"} href={"/favicon.ico"} />
          </Head>
        <body className={`${mont.variable} font-mont w-full min-h-screen`}>
            <NavBar />
            {children}
        </body>
      </html>
  )
}
